services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
  user_service:
    build: ./user-service
    volumes:
      - ./user-service/src:/usr/src/app/src
    command: npm run start:dev
  auth_service:
    build: ./auth-service
    volumes:
      - ./auth-service/src:/usr/src/app/src
    command: npm run start:dev
  email_service:
    build: ./email-service
    volumes:
      - ./email-service/src:/usr/src/app/src
    command: npm run start:dev
  activity_service:
    build: ./activity-service
    volumes:
      - ./activity-service/src:/usr/src/app/src
    command: npm run start:dev
  contract_service:
    build: ./contract-service
    volumes:
      - ./contract-service/src:/usr/src/app/src
    command: npm run start:dev
  customer_service:
    build: ./customer-service
    volumes:
      - ./customer-service/src:/usr/src/app/src
    command: npm run start:dev
  opportunity_service:
    build: ./opportunity-service
    volumes:
      - ./opportunity-service/src:/usr/src/app/src
    command: npm run start:dev
  price_quote_service:
    build: ./price_quote-service
    volumes:
      - ./price_quote-service/src:/usr/src/app/src
    command: npm run start:dev
  product_service:
    build: ./product-service
    volumes:
      - ./product-service/src:/usr/src/app/src
    command: npm run start:dev
  project_service:
    build: ./project-service
    volumes:
      - ./project-service/src:/usr/src/app/src
    command: npm run start:dev
  system_service:
    build: ./system-service
    volumes:
      - ./system-service/src:/usr/src/app/src
    command: npm run start:dev
